-- ============================================
-- Migración Postgres: Clientes y visibilidad
-- ============================================
-- Crea la tabla clientes y agrega id_cliente a usuarios y pulseras
-- Aplica reglas mínimas para visibilidad de perfiles
-- Ejecutar contra el mismo esquema donde existen las tablas actuales

DO $$
BEGIN
  -- Crear tabla clientes si no existe
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_name = 'clientes'
  ) THEN
    CREATE TABLE clientes (
      id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre_legal    VARCHAR(255) NOT NULL,
      nombre_publico  VARCHAR(255) NOT NULL,
      slug            VARCHAR(100) NOT NULL UNIQUE,
      id_fiscal       VARCHAR(64),
      contacto_email  VARCHAR(255),
      telefono        VARCHAR(64),
      direccion_linea1 VARCHAR(255),
      direccion_linea2 VARCHAR(255),
      direccion_ciudad VARCHAR(128),
      direccion_provincia VARCHAR(128),
      direccion_pais  VARCHAR(128),
      direccion_cp    VARCHAR(32),
      visibilidad     VARCHAR(16) NOT NULL DEFAULT 'publico', -- 'publico' | 'privado'
      estado          VARCHAR(16) NOT NULL DEFAULT 'activo',  -- 'activo' | 'suspendido'
      creado_en       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
      actualizado_en  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
    );
    CREATE UNIQUE INDEX idx_clientes_slug ON clientes (slug);
  END IF;

  -- Agregar columna id_cliente a usuarios si no existe
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name='usuarios' AND column_name='id_cliente'
  ) THEN
    ALTER TABLE usuarios
      ADD COLUMN id_cliente INTEGER NULL,
      ADD CONSTRAINT usuarios_cliente_fk
        FOREIGN KEY (id_cliente) REFERENCES clientes (id) ON DELETE SET NULL;
    CREATE INDEX IF NOT EXISTS idx_usuarios_id_cliente ON usuarios (id_cliente);
  END IF;

  -- Agregar columna rol a usuarios si no existe
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name='usuarios' AND column_name='rol'
  ) THEN
    ALTER TABLE usuarios
      ADD COLUMN rol VARCHAR(32) NOT NULL DEFAULT 'lector';
    -- Constraint simple para valores permitidos
    ALTER TABLE usuarios
      ADD CONSTRAINT usuarios_rol_check
      CHECK (rol IN ('admin_sistema', 'portador', 'lector'));
    -- Backfill básico: si tiene pulsera asociada, es portador; si no, lector
    UPDATE usuarios SET rol = 'portador' WHERE pulsera_id IS NOT NULL;
  END IF;

  -- Agregar columna id_cliente a pulseras si no existe
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name='pulseras' AND column_name='id_cliente'
  ) THEN
    ALTER TABLE pulseras
      ADD COLUMN id_cliente INTEGER NULL,
      ADD CONSTRAINT pulseras_cliente_fk
        FOREIGN KEY (id_cliente) REFERENCES clientes (id) ON DELETE SET NULL;
    CREATE INDEX IF NOT EXISTS idx_pulseras_id_cliente ON pulseras (id_cliente);
  END IF;
END$$;

-- Reglas de integridad básicas (una pulsera activa por usuario y viceversa ya se maneja con constraints existentes)


